export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdfa 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #fff9f4 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #f7f0fc 0%, #faf4fd 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #fffafc 0%, #fffdfd 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #e8fcf3 0%, #f5fffa 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)' },
  { id: 10,bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' },
];

export const APP_FEATURES = [
    {
        id:"01",
        title:"Tailored Just for You",
        description:
        "Get interview questions and model answers based on your role, experience and specific focus areas - no"
    },
    {
        id:"02",
        title:"Learn at Your Own Pace",
        description:
        "Expand answers only when you're ready. Dive deeper into anything you concept instantly with AI-powered detailed explanations."
    },
    {
        id:"03",
        title:"Capture Your Insights",
        description:
        "add personalized feedback on your answers, highlighting strengths and areas for improvement."
    },
    {
        id:"04",
        title:"Understand the 'Why'  Behind Answers",
        description:
        "Beyond just answers - unlock detailed explanations generated by AI to help you truly grasp concepts and techniques."
    },
    {
        id:"05",
        title:"Save, Organize, and Revisit",
        description:
        "Easily save your interview sets, Organize them by topic or difficulty level to create a personalized interview prep library at dashboard."
    },
]